typography_spectrum: 0.8388584386557341
color:
  brandColors:
    - '#334D5C'
    - '#45B29D'
    - '#EFC94C'
    - '#E27A3F'
    - '#DF5A49'
  brandStrength: 0.7491258755326271
  lightness: 0.6696048777084798
  saturation: 0.12005985714495182
  rhythmicContrast: 0.7966479621827602
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3501784363761544
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jennifer A. Yoder
  email: ''
name: Pittsburgh Peace Church
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2b7983aa-e1e6-4993-915f-fe176d768da0.jpg
title: Pittsburgh Peace Church
description: 'Gathering in Community: Working for Peace'
purpose: []
