name: Christian Peacemaker Teams
favicon: null
layout_spectrum: 0
typography_spectrum: 0.80019
title: Christian Peacemaker Teams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cf202f'
    - '#ffffff'
    - '#edada3'
    - '#dc5d61'
    - '#e38776'
  brandStrength: 0.75
  lightness: 0.6898446795530617
  saturation: 0.5066032619215548
  rhythmicContrast: 0.25
purpose: []
