typography_spectrum: 0.14627
color:
  brandColors:
    - '#cf202f'
    - '#ffffff'
    - '#edada3'
    - '#dc5d61'
    - '#e38776'
  brandStrength: 0.75
  lightness: 0.6898446795530617
  saturation: 0.5066032619215548
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Pittsburgh Peace Church
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Pittsburgh Peace Church
description: 'Gathering in Community: Working for Peace'
purpose: []
